var psjoblist = [
   {
      "JobId":"1666085406427",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"",
      "JobStatus":"Pending",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"",
      "JobRequestPayload":"{\"psreferencenumber\":null,\"psconfiguration\":null,\"psorientation\":null,\"psrims\":null,\"psbacksplash\":null,\"psendsplashleft\":null,\"psendsplashright\":null,\"psheater\":\"No\",\"psgeneration\":\"PS6\",\"psunitwidth\":30.0,\"psunitlength\":0.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"None\",\"psxxx\":null,\"psundershelf\":\"No Undershelf\",\"psovershelf\":\"No Overshelf\",\"psvoltage\":null,\"psovershelflength\":0.0,\"psovershelfheight\":0.0,\"psovershelfdistance\":0.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":0.0,\"pswashsinkwidth\":24.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":null},\"scrap\":{\"pssoildblength\":0.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":null,\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":0.0,\"psrinsesinkwidth\":24.75,\"psrinsesinkdepth\":0.0,\"psrinseoverflow\":null,\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":0.0,\"pssanitizesinkwidth\":24.75,\"pssanitizesinkdepth\":0.0,\"pssanitizeoverflow\":null,\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"18-10-2022 15:00:06",
      "JobInitiatedDate":"18-10-2022 15:00:06",
      "JobCompletedDate":"18-10-2022 15:00:06"
   },
   {
      "JobId":"1666069604053",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"job test",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"job test\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":30.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":24.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":\"PRE-RINSE 1/2in SPRAY VALVE\",\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":\"on\"},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":24.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"on\"},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":24.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":\"Standard Drain Ball Valve\",\"pssanitizefillfaucet\":\"on\"}}",
      "JobRequestedDate":"18-10-2022 10:36:44",
      "JobInitiatedDate":"18-10-2022 10:36:48",
      "JobCompletedDate":"18-10-2022 10:42:23"
   },
   {
      "JobId":"1665574634941",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":null,\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"9 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"90 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":\"PDF for user \",\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapSink\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"on\"},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":\"Standard Drain Ball Valve\",\"pssanitizefillfaucet\":\"on\"}}",
      "JobRequestedDate":"12-10-2022 17:07:14",
      "JobInitiatedDate":"12-10-2022 17:07:17",
      "JobCompletedDate":"12-10-2022 17:11:26"
   },
   {
      "JobId":"1665574165312",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":null,\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"Raw Edge\",\"psendsplashright\":\"Roll Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":30.0,\"psunitlength\":130.0,\"psdeckheight\":35.0,\"psfoottype\":\"Flange Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Welded Undershelf - Right Side\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"230V/1P\",\"psovershelflength\":50.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":30.0,\"pscrossrails\":\"Welded\",\"psdeck\":null,\"psdualtempering\":\"on\",\"pschemicaldispenser\":\"on\",\"psutensilbasket\":\"on\",\"psspecialcrating\":\"on\",\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":36.0,\"pswashsinkwidth\":24.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Security Drain Ball Valve\",\"psadvancedwashinsert\":\"on\",\"pssheetpanrack\":\"Full SS Sheet Pan Rack System ( 6, 10 & 14)\"},\"scrap\":{\"pssoildblength\":0.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":18.0,\"psrinsesinkwidth\":24.75,\"psrinsesinkdepth\":16.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":\"FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"off\"},\"sanitize\":{\"pssanitizesinklength\":20.0,\"pssanitizesinkwidth\":24.75,\"pssanitizesinkdepth\":19.0,\"pssanitizeoverflow\":\"Central Overflow\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":\"off\"}}",
      "JobRequestedDate":"12-10-2022 16:59:25",
      "JobInitiatedDate":"12-10-2022 16:59:28",
      "JobCompletedDate":"12-10-2022 17:04:07"
   },
   {
      "JobId":"1665573729187",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"",
      "JobStatus":"failedd",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"",
      "JobRequestPayload":"{\"psreferencenumber\":null,\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"Raw Edge\",\"psendsplashright\":\"Roll Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":30.0,\"psunitlength\":130.0,\"psdeckheight\":35.0,\"psfoottype\":\"Flange Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Welded Undershelf - Right Side\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"230V/1P\",\"psovershelflength\":50.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":30.0,\"pscrossrails\":\"Welded\",\"psdeck\":null,\"psdualtempering\":\"on\",\"pschemicaldispenser\":\"on\",\"psutensilbasket\":\"on\",\"psspecialcrating\":\"on\",\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":36.0,\"pswashsinkwidth\":24.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Security Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"Full SS Sheet Pan Rack System ( 6, 10 & 14)\"},\"scrap\":{\"pssoildblength\":0.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":18.0,\"psrinsesinkwidth\":24.75,\"psrinsesinkdepth\":16.0,\"psrinseoverflow\":\"Central Overflow\",\"psfillrinsetype\":\"FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"on\"},\"sanitize\":{\"pssanitizesinklength\":20.0,\"pssanitizesinkwidth\":24.75,\"pssanitizesinkdepth\":19.0,\"pssanitizeoverflow\":\"Central Overflow\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":\"on\"}}",
      "JobRequestedDate":"12-10-2022 16:52:09",
      "JobInitiatedDate":"12-10-2022 16:52:16",
      "JobCompletedDate":"12-10-2022 16:52:09"
   },
   {
      "JobId":"1665563366899",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"Faucet pc2",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"Faucet pc2\",\"psconfiguration\":\"Straight 2PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":\"Field Weld\",\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":\"PRE-RINSE 1/2in SPRAY VALVE\",\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":\"on\"},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"Central Overflow\",\"psfillrinsetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"on\"},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"Central Overflow\",\"psfillsanitizetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":\"Standard Drain Ball Valve\",\"pssanitizefillfaucet\":\"on\"}}",
      "JobRequestedDate":"12-10-2022 13:59:26",
      "JobInitiatedDate":"12-10-2022 13:59:35",
      "JobCompletedDate":"12-10-2022 14:03:14"
   },
   {
      "JobId":"1665562927327",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"Faucet",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"Faucet\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":\"PRE-RINSE 1/2in SPRAY VALVE\",\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":\"on\"},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"Central Overflow\",\"psfillrinsetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":\"Standard Drain Ball Valve\",\"psrinsefillfaucet\":\"on\"},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"Central Overflow\",\"psfillsanitizetype\":\"FAUCET 3/4in WALL MOUNT 12 SPOUT\",\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":\"Standard Drain Ball Valve\",\"pssanitizefillfaucet\":\"on\"}}",
      "JobRequestedDate":"12-10-2022 13:52:07",
      "JobInitiatedDate":"12-10-2022 13:52:27",
      "JobCompletedDate":"12-10-2022 13:56:54"
   },
   {
      "JobId":"1665560202424",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"kjk",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"kjk\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"12-10-2022 13:06:42",
      "JobInitiatedDate":"12-10-2022 13:06:50",
      "JobCompletedDate":"12-10-2022 13:11:00"
   },
   {
      "JobId":"1665559846681",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"kjk",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"kjk\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"12-10-2022 13:00:46",
      "JobInitiatedDate":"12-10-2022 13:01:06",
      "JobCompletedDate":"12-10-2022 13:05:05"
   },
   {
      "JobId":"1665557777267",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"kjk",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"kjk\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"12-10-2022 12:26:17",
      "JobInitiatedDate":"12-10-2022 12:47:55",
      "JobCompletedDate":"12-10-2022 12:52:01"
   },
   {
      "JobId":"1665496757471",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"test",
      "JobStatus":"Completed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"Model Generated successfully @D:\\SWAutomation\\Final UB PSPE Automation",
      "JobRequestPayload":"{\"psreferencenumber\":\"test\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"No Undershelf\",\"psovershelf\":\"No Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"11-10-2022 19:29:17",
      "JobInitiatedDate":"11-10-2022 19:29:39",
      "JobCompletedDate":"11-10-2022 19:33:33"
   },
   {
      "JobId":"1665495435148",
      "JobRequestedUser":"PowerSoakAutomation",
      "JobDesc":"test",
      "JobStatus":"failed",
      "JobFolder":"",
      "JobGeneratedFilePdf":"",
      "JobGeneratedFileModel":"",
      "JobExecutionLogs":"",
      "JobRequestPayload":"{\"psreferencenumber\":\"test\",\"psconfiguration\":\"Straight 1PC\",\"psorientation\":\"Left to Right\",\"psrims\":\"SQR Rim\",\"psbacksplash\":\"Up Bs\",\"psendsplashleft\":\"1 Es\",\"psendsplashright\":\"1 Es\",\"psheater\":\"Yes\",\"psgeneration\":\"PS6\",\"psunitwidth\":34.0,\"psunitlength\":150.0,\"psdeckheight\":35.0,\"psfoottype\":\"Bullet Foot\",\"psdryingrack\":\"8 Pans\",\"psxxx\":\"PS-200 STANDARD CONTROL W/HEAT\",\"psundershelf\":\"Right Undershelf\",\"psovershelf\":\"45 Degree Overshelf\",\"psvoltage\":\"208V/1P\",\"psovershelflength\":100.0,\"psovershelfheight\":85.0,\"psovershelfdistance\":25.0,\"pscrossrails\":\"Brace Mount\",\"psdeck\":null,\"psdualtempering\":null,\"pschemicaldispenser\":null,\"psutensilbasket\":null,\"psspecialcrating\":null,\"psspecialnotes\":null,\"psjointtype\":null,\"wash\":{\"pswashsinklength\":42.0,\"pswashsinkwidth\":28.75,\"pswashsinkdepth\":21.0,\"pswashsinkdraintype\":\"Standard Drain Ball Valve\",\"psadvancedwashinsert\":\"No\",\"pssheetpanrack\":\"No Rack Assembly\"},\"scrap\":{\"pssoildblength\":5.0,\"pssdsinklength\":12.0,\"pssdsinkwidth\":22.75,\"pssdsinkdepth\":4.0,\"pssdsinkwaterinlet\":\"None\",\"psscrapperdraintype\":\"Left Rear\",\"psdisposerpstype\":null,\"psdisposerexttype\":null,\"psdrainboarddiff\":0.0,\"psprerinsetype\":null,\"psprerinsecompany\":\"T&S\",\"psscrapperdisposerunit\":\"ScrapperUnit\",\"psprerinsefaucet\":null},\"rinse\":{\"psrinsesinklength\":24.0,\"psrinsesinkwidth\":28.75,\"psrinsesinkdepth\":14.0,\"psrinseoverflow\":\"None\",\"psfillrinsetype\":null,\"psfillrinsecompany\":\"T&S\",\"psrinsesinkdraintype\":null,\"psrinsefillfaucet\":null},\"sanitize\":{\"pssanitizesinklength\":22.0,\"pssanitizesinkwidth\":28.75,\"pssanitizesinkdepth\":14.0,\"pssanitizeoverflow\":\"None\",\"psfillsanitizetype\":null,\"psfillsanitizecompany\":\"T&S\",\"pssanitizesinkdraintype\":null,\"pssanitizefillfaucet\":null}}",
      "JobRequestedDate":"11-10-2022 19:07:15",
      "JobInitiatedDate":"11-10-2022 19:19:42",
      "JobCompletedDate":"11-10-2022 19:07:15"
   }
]

export { psjoblist };
