var referencedata = {
  Orientation: [
    {
      id: 1,
      category: "Orientation",
      categoryId: "1",
      value: "Left to Right",
      desc: "Left to Right",
      hide: "n",
    },
    {
      id: 2,
      category: "Orientation",
      categoryId: "2",
      value: "Right to Left",
      desc: "Right to Left",
      hide: "n",
    },
  ],
  Configuration: [
    {
      id: 3,
      category: "Configuration",
      categoryId: "1",
      value: "Straight 1PC",
      desc: "Straight One-Piece Construction",
      hide: "n",
    },
    {
      id: 4,
      category: "Configuration",
      categoryId: "2",
      value: "Straight 2PC",
      desc: "Straight Two-Piece Construction",
      hide: "n",
    },
    {
      id: 5,
      category: "Configuration",
      categoryId: "3",
      value: "L",
      desc: "L Shape",
      hide: "n",
    },
    {
      id: 6,
      category: "Configuration",
      categoryId: "4",
      value: "U",
      desc: "U Shape",
      hide: "n",
    },
  ],
  Rim: [
    {
      id: 7,
      category: "Rim",
      categoryId: "1",
      value: "SQR Rim",
      desc: "Square Channel Rim",
      hide: "n",
    },
    {
      id: 8,
      category: "Rim",
      categoryId: "2",
      value: "Roll Rim",
      desc: "Rolled Rim",
      hide: "n",
    },
  ],
  BackSplash: [
    {
      id: 9,
      category: "BackSplash",
      categoryId: "1",
      value: "Up Bs",
      desc: "Turned UP Backsplash",
      hide: "n",
    },
    {
      id: 10,
      category: "BackSplash",
      categoryId: "2",
      value: "Down Bs",
      desc: "Turned Down Backsplash",
      hide: "n",
    },
  ],
  EndSplashLeft: [
    {
      id: 12,
      category: "EndSplashLeft",
      categoryId: "1",
      value: "SQR Es",
      desc: "Square Channel Rim",
      hide: "n",
    },
    {
      id: 13,
      category: "EndSplashLeft",
      categoryId: "2",
      value: "Roll Es",
      desc: "Rolled Rim",
      hide: "n",
    },
    {
      id: 14,
      category: "EndSplashLeft",
      categoryId: "3",
      value: "Up Es",
      desc: 'Turned Up 2" End Splash',
      hide: "n",
    },
    {
      id: 15,
      category: "EndSplashLeft",
      categoryId: "4",
      value: "Down Es",
      desc: 'Turned Down 2" End Splash',
      hide: "n",
    },
    {
      id: 16,
      category: "EndSplashLeft",
      categoryId: "5",
      value: "1 Es",
      desc: '1" Square End Splash',
      hide: "n",
    },
    {
      id: 17,
      category: "EndSplashLeft",
      categoryId: "6",
      value: "Hem Es",
      desc: "Hemmed End Splash",
      hide: "n",
    },
    // {
    //    "id":351,
    //    "category":"EndSplashLeft",
    //    "categoryId":"7",
    //    "value":"Raw Edge",
    //    "desc":"Raw Edge",
    //    "hide":"n"
    // },
    // {
    //    "id":352,
    //    "category":"EndSplashLeft",
    //    "categoryId":"8",
    //    "value":"Lip To dish machine",
    //    "desc":"Lip To dish machine",
    //    "hide":"n"
    // }
  ],
  EndSplashRight: [
    {
      id: 18,
      category: "EndSplashRight",
      categoryId: "1",
      value: "SQR Es",
      desc: "Square Channel Rim",
      hide: "n",
    },
    {
      id: 19,
      category: "EndSplashRight",
      categoryId: "2",
      value: "Roll Es",
      desc: "Rolled Rim",
      hide: "n",
    },
    {
      id: 20,
      category: "EndSplashRight",
      categoryId: "3",
      value: "Up Es",
      desc: 'Turned Up 2" End Splash',
      hide: "n",
    },
    {
      id: 21,
      category: "EndSplashRight",
      categoryId: "4",
      value: "Down Es",
      desc: 'Turned Down 2" End Splash',
      hide: "n",
    },
    {
      id: 22,
      category: "EndSplashRight",
      categoryId: "5",
      value: "1 Es",
      desc: '1" Square End Splash',
      hide: "n",
    },
    {
      id: 23,
      category: "EndSplashRight",
      categoryId: "6",
      value: "Hem Es",
      desc: "Hemmed End Splash",
      hide: "n",
    },
    // {
    //    "id":353,
    //    "category":"EndSplashRight",
    //    "categoryId":"7",
    //    "value":"Raw Edge",
    //    "desc":"Raw Edge",
    //    "hide":"n"
    // },
    // {
    //    "id":354,
    //    "category":"EndSplashRight",
    //    "categoryId":"8",
    //    "value":"Lip To dish machine",
    //    "desc":"Lip To dish machine",
    //    "hide":"n"
    // }
  ],
  UnitWidth: [
    {
      id: 24,
      category: "UnitWidth",
      categoryId: "1",
      value: "30",
      desc: '30"',
      hide: "n",
    },
    {
      id: 25,
      category: "UnitWidth",
      categoryId: "2",
      value: "34",
      desc: '34"',
      hide: "n",
    },
    {
      id: 26,
      category: "UnitWidth",
      categoryId: "3",
      value: "37",
      desc: '37"',
      hide: "n",
    },
  ],
  Deckheight: [
    {
      id: 28,
      category: "Deckheight",
      categoryId: "2",
      value: "35",
      desc: '35"',
      hide: "n",
    },
  ],
  JointType: [
    // {
    //    "id":29,
    //    "category":"JointType",
    //    "categoryId":"1",
    //    "value":"1PC",
    //    "desc":"One-Piece Construction",
    //    "hide":"n"
    // },
    {
      id: 30,
      category: "JointType",
      categoryId: "2",
      value: "JBZ",
      desc: "JBZ Mechanical Joint",
      hide: "n",
    },
    {
      id: 31,
      category: "JointType",
      categoryId: "3",
      value: "Field Weld",
      desc: "Field Weld",
      hide: "n",
    },
  ],
  ScrapSinkLength: [
    {
      id: 32,
      category: "ScrapSinkLength",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },
    {
      id: 33,
      category: "ScrapSinkLength",
      categoryId: "2",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 34,
      category: "ScrapSinkLength",
      categoryId: "3",
      value: "20",
      desc: '20"',
      hide: "n",
    },
    {
      id: 35,
      category: "ScrapSinkLength",
      categoryId: "4",
      value: "24",
      desc: '24"',
      hide: "n",
    },
    {
      id: 36,
      category: "ScrapSinkLength",
      categoryId: "5",
      value: "28",
      desc: '28"',
      hide: "n",
    },
    {
      id: 37,
      category: "ScrapSinkLength",
      categoryId: "6",
      value: "36",
      desc: '36"',
      hide: "n",
    },
  ],
  ScrapSinkLengthcustomer: [
    {
      id: 32,
      category: "ScrapSinkLength",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },

    {
      id: 35,
      category: "ScrapSinkLength",
      categoryId: "5",
      value: "24",
      desc: '24"',
      hide: "n",
    },
  ],
  ScrapSinkWidth: [
    {
      id: 38,
      category: "ScrapSinkWidth",
      categoryId: "2",
      value: "22.75",
      desc: '22.75"',
      hide: "n",
    },
  ],
  ScrapSinkDepth: [
    {
      id: 42,
      category: "ScrapSinkDepth",
      categoryId: "1",
      value: "4",
      desc: '4"',
      hide: "n",
    },
  ],
  SinkWaterInlet: [
    {
      id: 45,
      category: "SinkWaterInlet",
      categoryId: "1",
      value: "Left Wall",
      desc: "Left Wall",
      hide: "n",
    },
    {
      id: 46,
      category: "SinkWaterInlet",
      categoryId: "2",
      value: "Right Wall",
      desc: "Right Wall",
      hide: "n",
    },
    {
      id: 47,
      category: "SinkWaterInlet",
      categoryId: "3",
      value: "Rear Wall",
      desc: "Rear Wall",
      hide: "n",
    },
    {
      id: 48,
      category: "SinkWaterInlet",
      categoryId: "4",
      value: "Left and Right Wall",
      desc: "Left and Right Wall",
      hide: "n",
    },
    {
      id: 49,
      category: "SinkWaterInlet",
      categoryId: "5",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  ScrapSPanRack42inkDrain: [
    {
      id: 50,
      category: "ScrapSinkDrain",
      categoryId: "1",
      value: "Center(2in)",
      desc: "Center(2in)",
      hide: "n",
    },
    {
      id: 52,
      category: "ScrapSinkDrain",
      categoryId: "3",
      value: "Right Rear",
      desc: "Right Rear",
      hide: "n",
    },
    {
      id: 53,
      category: "ScrapSinkDrain",
      categoryId: "4",
      value: "Left Rear",
      desc: "Left Rear",
      hide: "n",
    },
  ],
  DisposerCollarSize: [
    {
      id: 54,
      category: "DisposerCollarSize",
      categoryId: "1",
      value: "SALVAJOR 6.5",
      desc: "SALVAJOR 6.5",
      hide: "n",
    },
    {
      id: 56,
      category: "DisposerCollarSize",
      categoryId: "3",
      value: "ISE #5",
      desc: "ISE #5",
      hide: "n",
    },
    {
      id: 57,
      category: "DisposerCollarSize",
      categoryId: "4",
      value: "ISE #6",
      desc: "ISE #6",
      hide: "n",
    },
    {
      id: 58,
      category: "DisposerCollarSize",
      categoryId: "5",
      value: "ISE #7",
      desc: "ISE #7",
      hide: "n",
    },
    {
      id: 59,
      category: "DisposerCollarSize",
      categoryId: "6",
      value: "Hobart 7",
      desc: "Hobart 7",
      hide: "n",
    },
  ],
  DisposerExtDrain: [
    {
      id: 60,
      category: "DisposerExtDrain",
      categoryId: "1",
      value: "ISE 12in",
      desc: "ISE 12in",
      hide: "n",
    },
    {
      id: 61,
      category: "DisposerExtDrain",
      categoryId: "2",
      value: " REDGOAT 12in",
      desc: " REDGOAT 12in",
      hide: "n",
    },
    {
      id: 62,
      category: "DisposerExtDrain",
      categoryId: "3",
      value: "SALVAJOR 12in",
      desc: "SALVAJOR 12in",
      hide: "n",
    },
    {
      id: 63,
      category: "DisposerExtDrain",
      categoryId: "4",
      value: "SOMAT 12in",
      desc: "SOMAT 12in",
      hide: "n",
    },
    {
      id: 64,
      category: "DisposerExtDrain",
      categoryId: "5",
      value: "HOBART 15in",
      desc: "HOBART 15in",
      hide: "n",
    },
    {
      id: 65,
      category: "DisposerExtDrain",
      categoryId: "6",
      value: "ISE 15in",
      desc: "ISE 15in",
      hide: "n",
    },
    {
      id: 66,
      category: "DisposerExtDrain",
      categoryId: "7",
      value: " REDGOAT 15in",
      desc: " REDGOAT 15in",
      hide: "n",
    },
    {
      id: 67,
      category: "DisposerExtDrain",
      categoryId: "8",
      value: "SALVAJOR 15in",
      desc: "SALVAJOR 15in",
      hide: "n",
    },
    {
      id: 68,
      category: "DisposerExtDrain",
      categoryId: "9",
      value: "HOBART 18in",
      desc: "HOBART 18in",
      hide: "n",
    },
    {
      id: 69,
      category: "DisposerExtDrain",
      categoryId: "10",
      value: "ISE 18in",
      desc: "ISE 18in",
      hide: "n",
    },
    {
      id: 70,
      category: "DisposerExtDrain",
      categoryId: "11",
      value: "MASTER 18in",
      desc: "MASTER 18in",
      hide: "n",
    },
    {
      id: 71,
      category: "DisposerExtDrain",
      categoryId: "12",
      value: " REDGOAT 18in",
      desc: " REDGOAT 18in",
      hide: "n",
    },
    {
      id: 72,
      category: "DisposerExtDrain",
      categoryId: "13",
      value: "SALVAJOR 18in",
      desc: "SALVAJOR 18in",
      hide: "n",
    },
    {
      id: 73,
      category: "DisposerExtDrain",
      categoryId: "14",
      value: "SOMAT 18in",
      desc: "SOMAT 18in",
      hide: "n",
    },
    {
      id: 74,
      category: "DisposerExtDrain",
      categoryId: "15",
      value: " WASTEKING 18in",
      desc: " WASTEKING 18in",
      hide: "n",
    },
  ],
  PreRinseFaucet: [
    {
      id: 75,
      category: "PreRinseFaucet",
      categoryId: "1",
      value: "PRE-RINSE 1/2in SPRAY VALVE",
      desc: "PRE-RINSE 1/2in SPRAY VALVE",
      hide: "n",
    },
    {
      id: 76,
      category: "PreRinseFaucet",
      categoryId: "2",
      value: "PRE-RINSE 1/2in WALL MOUNT QUICK DISCONNECT",
      desc: "PRE-RINSE 1/2in WALL MOUNT QUICK DISCONNECT",
      hide: "n",
    },
    {
      id: 77,
      category: "PreRinseFaucet",
      categoryId: "3",
      value: "PRE-RINSE 1/2in WALL MOUNT SPRAY VALVE SECURITY",
      desc: "PRE-RINSE 1/2in WALL MOUNT SPRAY VALVE SECURITY",
      hide: "n",
    },
    {
      id: 364,
      category: "PreRinseFaucet",
      categoryId: "5",
      value: "PRE-RINSE W/COMBO FAUCET 1/2in SPRAY VALVE",
      desc: "PRE-RINSE W/COMBO FAUCET 1/2in SPRAY VALVE",
      hide: "n",
    },
    {
      id: 365,
      category: "PreRinseFaucet",
      categoryId: "6",
      value: "PRE-RINSE W/COMBO FAUCET 1/2in WALL MOUNT QUICK DISCONNECT",
      desc: "PRE-RINSE W/COMBO FAUCET 1/2in WALL MOUNT QUICK DISCONNECT",
      hide: "n",
    },
    {
      id: 366,
      category: "PreRinseFaucet",
      categoryId: "7",
      value: "PRE-RINSE W/COMBO FAUCET 1/2in WALL MOUNT SPRAY VALVE SECURITY",
      desc: "PRE-RINSE W/COMBO FAUCET 1/2in WALL MOUNT SPRAY VALVE SECURITY",
      hide: "n",
    },
    {
      id: 367,
      category: "PreRinseFaucet",
      categoryId: "8",
      value: "PRE-RINSE 3/4in  SPRAY VALVE",
      desc: "PRE-RINSE 3/4in  SPRAY VALVE",
      hide: "n",
    },
    {
      id: 368,
      category: "PreRinseFaucet",
      categoryId: "9",
      value: "PRE-RINSE  3/4in WALL MOUNT QUICK DISCONNECT",
      desc: "PRE-RINSE  3/4in WALL MOUNT QUICK DISCONNECT",
      hide: "n",
    },
    {
      id: 369,
      category: "PreRinseFaucet",
      categoryId: "10",
      value: "PRE-RINSE  3/4in WALL MOUNT SPRAY VALVE SECURITY",
      desc: "PRE-RINSE  3/4in WALL MOUNT SPRAY VALVE SECURITY",
      hide: "n",
    },
    {
      id: 370,
      category: "PreRinseFaucet",
      categoryId: "11",
      value: "PRE-RINSE W/COMBO FAUCET 3/4in SPRAY VALVE",
      desc: "PRE-RINSE W/COMBO FAUCET 3/4in SPRAY VALVE",
      hide: "n",
    },
    {
      id: 371,
      category: "PreRinseFaucet",
      categoryId: "12",
      value: "PRE-RINSE  W/COMBO FAUCET 3/4in WALL MOUNT QUICK DISCONNECT",
      desc: "PRE-RINSE  W/COMBO FAUCET 3/4in WALL MOUNT QUICK DISCONNECT",
      hide: "n",
    },
    {
      id: 372,
      category: "PreRinseFaucet",
      categoryId: "13",
      value: "PRE-RINSE  W/COMBO FAUCET 3/4in WALL MOUNT SPRAY VALVE SECURITY",
      desc: "PRE-RINSE  W/COMBO FAUCET 3/4in WALL MOUNT SPRAY VALVE SECURITY",
      hide: "n",
    },
    {
      id: 373,
      category: "PreRinseFaucet",
      categoryId: "14",
      value: "FAUCETS BY OTHERS",
      desc: "FAUCETS BY OTHERS",
      hide: "n",
    },
  ],
  PreRinseCompany: [
    {
      id: 79,
      category: "PreRinseCompany",
      categoryId: "1",
      value: "T&S",
      desc: "T&S",
      hide: "n",
    },
    {
      id: 80,
      category: "PreRinseCompany",
      categoryId: "2",
      value: "Encore",
      desc: "Encore",
      hide: "n",
    },
  ],
  WashSinkLength: [
    {
      id: 84,
      category: "WashSinkLength",
      categoryId: "4",
      value: "30",
      desc: '30"',
      hide: "n",
    },
    {
      id: 85,
      category: "WashSinkLength",
      categoryId: "5",
      value: "36",
      desc: '36"',
      hide: "n",
    },
    {
      id: 86,
      category: "WashSinkLength",
      categoryId: "6",
      value: "42",
      desc: '42"',
      hide: "n",
    },
    {
      id: 87,
      category: "WashSinkLength",
      categoryId: "7",
      value: "48",
      desc: '48"',
      hide: "n",
    },
  ],
  WashSinkLengthTwo: [
    {
      id: 88,
      category: "WashSinkLength",
      categoryId: "8",
      value: "54",
      desc: '54"',
      hide: "n",
    },
    {
      id: 89,
      category: "WashSinkLength",
      categoryId: "9",
      value: "60",
      desc: '60"',
      hide: "n",
    },
    {
      id: 90,
      category: "WashSinkLength",
      categoryId: "10",
      value: "66",
      desc: '66"',
      hide: "n",
    },
    {
      id: 91,
      category: "WashSinkLength",
      categoryId: "11",
      value: "72",
      desc: '72"',
      hide: "n",
    },
  ],
  WashSinkWidth: [
    {
      id: 94,
      category: "WashSinkWidth",
      categoryId: "3",
      value: "24.75",
      desc: '24.75"',
      hide: "n",
    },
    {
      id: 96,
      category: "WashSinkWidth",
      categoryId: "5",
      value: "28.75",
      desc: '28.75"',
      hide: "n",
    },
    {
      id: 97,
      category: "WashSinkWidth",
      categoryId: "6",
      value: "31.75",
      desc: '31.75"',
      hide: "n",
    },
  ],
  WashSinkDepth: [
    {
      id: 104,
      category: "WashSinkDepth",
      categoryId: "5",
      value: "21",
      desc: '21"',
      hide: "n",
    },
  ],
  PanRack30: [
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 3 & 6)",
      hide: "n",
    },
    {
      id: 438,
      category: "PanRack",
      categoryId: "18",
      value: "First Rack Assembly Only",
      desc: "3 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 439,
      category: "PanRack",
      categoryId: "19",
      value: "Last Rack Assembly Only",
      desc: "6 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack36: [
    {
      id: 403,
      category: "PanRack",
      categoryId: "3",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 3 & 10)",
      hide: "n",
    },

    {
      id: 438,
      category: "PanRack",
      categoryId: "18",
      value: "First Rack Assembly Only",
      desc: "3 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "Last Rack Assembly Only",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack42: [
    {
      id: 404,
      category: "PanRack",
      categoryId: "4",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6 & 10)",
      hide: "n",
    },
    {
      id: 439,
      category: "PanRack",
      categoryId: "19",
      value: "First Rack Assembly Only",
      desc: "6 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "Last Rack Assembly Only",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack48: [
    {
      id: 405,
      category: "PanRack",
      categoryId: "5",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6 & 14)",
      hide: "n",
    },
    {
      id: 439,
      category: "PanRack",
      categoryId: "19",
      value: "First Rack Assembly Only",
      desc: "6 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "Last Rack Assembly Only",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack54: [
    {
      id: 407,
      category: "PanRack",
      categoryId: "6",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 10 & 14)",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "First Rack Assembly Only",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "Last Rack Assembly Only",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack60: [
    {
      id: 408,
      category: "PanRack",
      categoryId: "7",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 14 & 14)",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "First Rack Assembly Only",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
  ],
  PanRack66: [
    {
      id: 411,
      category: "PanRack",
      categoryId: "8",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6, 10 & 14)",
      hide: "n",
    },
    {
      id: 439,
      category: "PanRack",
      categoryId: "19",
      value: "First Rack Assembly Only",
      desc: "6 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "First Rack Assembly Only",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "Last Rack Assembly Only",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  PanRack72: [
    {
      id: 413,
      category: "PanRack",
      categoryId: "9",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 10, 10 & 14)",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "First Rack Assembly Only",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "Last Rack Assembly Only",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
  ],
  PanRack: [
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 3 & 6)",
      hide: "n",
    },
    {
      id: 403,
      category: "PanRack",
      categoryId: "3",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 3 & 10)",
      hide: "n",
    },
    {
      id: 404,
      category: "PanRack",
      categoryId: "4",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6 & 10)",
      hide: "n",
    },
    {
      id: 405,
      category: "PanRack",
      categoryId: "5",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6 & 14)",
      hide: "n",
    },
    {
      id: 407,
      category: "PanRack",
      categoryId: "6",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 10 & 14)",
      hide: "n",
    },
    {
      id: 408,
      category: "PanRack",
      categoryId: "7",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 14 & 14)",
      hide: "n",
    },
    {
      id: 411,
      category: "PanRack",
      categoryId: "8",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 6, 10 & 14)",
      hide: "n",
    },
    {
      id: 413,
      category: "PanRack",
      categoryId: "9",
      value: "Complete Rack Assembly",
      desc: "Full SS Sheet Pan Rack System ( 10, 10 & 14)",
      hide: "n",
    },
    {
      id: 438,
      category: "PanRack",
      categoryId: "18",
      value: "3 Sheet Pan Rack Set",
      desc: "3 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 439,
      category: "PanRack",
      categoryId: "19",
      value: "6 Sheet Pan Rack Set",
      desc: "6 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 440,
      category: "PanRack",
      categoryId: "20",
      value: "10 Sheet Pan Rack Set",
      desc: "10 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 441,
      category: "PanRack",
      categoryId: "21",
      value: "14 Sheet Pan Rack Set",
      desc: "14 SS Sheet Pan Rack Set",
      hide: "n",
    },
    {
      id: 402,
      category: "PanRack",
      categoryId: "2",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  WashDrain: [
    {
      id: 109,
      category: "WashDrain",
      categoryId: "1",
      value: "Standard Drain Ball Valve",
      desc: "Drain Valve Rear Exit",
      hide: "n",
    },
    {
      id: 110,
      category: "WashDrain",
      categoryId: "2",
      value: "Security Drain Ball Valve",
      desc: "Security Drain Ball Valve",
      hide: "n",
    },
    // {
    //    "id":111,
    //    "category":"WashDrain",
    //    "categoryId":"3",
    //    "value":"Pop-Up Drain",
    //    "desc":"Pop-Up Drain",
    //    "hide":"n"
    // }
  ],
  RinseSinklength: [
    {
      id: 112,
      category: "RinseSinklength",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },
    {
      id: 113,
      category: "RinseSinklength",
      categoryId: "2",
      value: "14",
      desc: '14"',
      hide: "n",
    },
    {
      id: 115,
      category: "RinseSinklength",
      categoryId: "4",
      value: "16",
      desc: '16"',
      hide: "n",
    },
    {
      id: 118,
      category: "RinseSinklength",
      categoryId: "7",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 121,
      category: "RinseSinklength",
      categoryId: "10",
      value: "20",
      desc: '20"',
      hide: "n",
    },
    {
      id: 123,
      category: "RinseSinklength",
      categoryId: "12",
      value: "22",
      desc: '22"',
      hide: "n",
    },
    {
      id: 126,
      category: "RinseSinklength",
      categoryId: "15",
      value: "24",
      desc: '24"',
      hide: "n",
    },
    {
      id: 128,
      category: "RinseSinklength",
      categoryId: "17",
      value: "26",
      desc: '26"',
      hide: "n",
    },
    {
      id: 131,
      category: "RinseSinklength",
      categoryId: "20",
      value: "28",
      desc: '28"',
      hide: "n",
    },
    {
      id: 135,
      category: "RinseSinklength",
      categoryId: "24",
      value: "30",
      desc: '30"',
      hide: "n",
    },
    {
      id: 139,
      category: "RinseSinklength",
      categoryId: "28",
      value: "36",
      desc: '36"',
      hide: "n",
    },
  ],
  RinseSinkWidth: [
    {
      id: 142,
      category: "RinseSinkWidth",
      categoryId: "2",
      value: "24.75",
      desc: '24.75"',
      hide: "n",
    },
    {
      id: 144,
      category: "RinseSinkWidth",
      categoryId: "4",
      value: "28.75",
      desc: '28.75"',
      hide: "n",
    },
    {
      id: 145,
      category: "RinseSinkWidth",
      categoryId: "5",
      value: "31.75",
      desc: '31.75"',
      hide: "n",
    },
  ],
  RinseSinkDepth: [
    {
      id: 149,
      category: "RinseSinkDepth",
      categoryId: "3",
      value: "14",
      desc: '14"',
      hide: "n",
    },
    {
      id: 150,
      category: "RinseSinkDepth",
      categoryId: "4",
      value: "16",
      desc: '16"',
      hide: "n",
    },
    {
      id: 151,
      category: "RinseSinkDepth",
      categoryId: "5",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 153,
      category: "RinseSinkDepth",
      categoryId: "7",
      value: "21",
      desc: '21"',
      hide: "n",
    },
  ],
  RinseOverflow: [
    {
      id: 155,
      category: "RinseOverflow",
      categoryId: "1",
      value: "NONE",
      desc: "No",
      hide: "n",
    },
    {
      id: 156,
      category: "RinseOverflow",
      categoryId: "2",
      value: "Central Overflow",
      desc: "Yes",
      hide: "n",
    },
  ],
  RinseDrain: [
    {
      id: 159,
      category: "RinseDrain",
      categoryId: "1",
      value: "Standard Drain Ball Valve",
      desc: "Drain Valve Rear Exit",
      hide: "n",
    },
    {
      id: 160,
      category: "RinseDrain",
      categoryId: "2",
      value: "Security Drain Ball Valve",
      desc: "Security Drain Ball Valve",
      hide: "n",
    },
    {
      id: 161,
      category: "RinseDrain",
      categoryId: "3",
      value: "Overflow Drain Ball Valve",
      desc: "Overflow Drain Ball Valve",
      hide: "n",
    },
    // {
    //    "id":442,
    //    "category":"RinseDrain",
    //    "categoryId":"4",
    //    "value":"Pop-Up Drain",
    //    "desc":"Pop-Up Drain",
    //    "hide":"n"
    // }
  ],
  RinseDraincondition: [
    {
      id: 161,
      category: "RinseDrain",
      categoryId: "3",
      value: "Overflow Drain Ball Valve",
      desc: "Overflow Drain Ball Valve",
      hide: "n",
    },
  ],
  RinseFaucet: [
    {
      id: 162,
      category: "RinseFaucet",
      categoryId: "1",
      value: "FAUCET 3/4in WALL MOUNT 12 SPOUT",
      desc: "FAUCET 3/4in WALL MOUNT 12 SPOUT",
      hide: "n",
    },
    {
      id: 509,
      category: "RinseFaucet",
      categoryId: "2",
      value: "FAUCET 3/4in WALL MOUNT 14 SPOUT",
      desc: "FAUCET 3/4in WALL MOUNT 14 SPOUT",
      hide: "n",
    },
    {
      id: 163,
      category: "RinseFaucet",
      categoryId: "3",
      value: "FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT",
      desc: "FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT",
      hide: "n",
    },
    {
      id: 510,
      category: "RinseFaucet",
      categoryId: "4",
      value: "FAUCET SECURITY 3/4in WALL MOUNT 14 SPOUT",
      desc: "FAUCET SECURITY 3/4in WALL MOUNT 14 SPOUT",
      hide: "n",
    },
    {
      id: 165,
      category: "RinseFaucet",
      categoryId: "5",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      hide: "n",
    },
    {
      id: 166,
      category: "RinseFaucet",
      categoryId: "6",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT QD ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT QD ACCSY FITTING",
      hide: "n",
    },
    {
      id: 167,
      category: "RinseFaucet",
      categoryId: "7",
      value: "PRE-RINSE 3/4 COMBO T&S B-0287-PS-OH-VR(Only T&S)",
      desc: "PRE-RINSE 3/4 COMBO T&S B-0287-PS-OH-VR(Only T&S)",
      hide: "n",
    },
    {
      id: 168,
      category: "RinseFaucet",
      categoryId: "8",
      value: "PRE-RINSE 1/2 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      desc: "PRE-RINSE 1/2 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      hide: "n",
    },
    {
      id: 169,
      category: "RinseFaucet",
      categoryId: "9",
      value: "PRE-RINSE 1/2 COMBO W/40IFLEX HOSE QD(Only T&S)",
      desc: "PRE-RINSE 1/2 COMBO W/40IFLEX HOSE QD(Only T&S)",
      hide: "n",
    },
    {
      id: 170,
      category: "RinseFaucet",
      categoryId: "10",
      value: "PRE-RINSE 1/2 COMBO T&S B-2475-PS-OH-VR(Only T&S)",
      desc: "PRE-RINSE 1/2 COMBO T&S B-2475-PS-OH-VR(Only T&S)",
      hide: "n",
    },
    {
      id: 171,
      category: "RinseFaucet",
      categoryId: "11",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 12 SPOUT QD ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 12 SPOUT QD ACCSY FITTING",
      hide: "n",
    },
    {
      id: 172,
      category: "RinseFaucet",
      categoryId: "12",
      value: "PRE-RINSE 1/2 COMBO WALL MOUNT SPRAY VALVE 14 SPOUT VAC BRKR",
      desc: "PRE-RINSE 1/2 COMBO WALL MOUNT SPRAY VALVE 14 SPOUT VAC BRKR",
      hide: "n",
    },
    {
      id: 373,
      category: "PreRinseFaucet",
      categoryId: "13",
      value: "FAUCETS BY OTHERS",
      desc: "FAUCETS BY OTHERS",
      hide: "n",
    },
  ],
  RinseCompany: [
    {
      id: 173,
      category: "RinseCompany",
      categoryId: "1",
      value: "T&S",
      desc: "T&S",
      hide: "n",
    },
    {
      id: 174,
      category: "RinseCompany",
      categoryId: "2",
      value: "Encore",
      desc: "Encore",
      hide: "n",
    },
  ],
  SanitizeSinkLength: [
    {
      id: 173,
      category: "SanitizeSinkLength",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },
    {
      id: 174,
      category: "SanitizeSinkLength",
      categoryId: "2",
      value: "14",
      desc: '14"',
      hide: "n",
    },

    {
      id: 174,
      category: "SanitizeSinkLength",
      categoryId: "2",
      value: "16",
      desc: '16"',
      hide: "n",
    },
    {
      id: 175,
      category: "SanitizeSinkLength",
      categoryId: "1",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 176,
      category: "SanitizeSinkLength",
      categoryId: "2",
      value: "19",
      desc: '19"',
      hide: "n",
    },
    {
      id: 177,
      category: "SanitizeSinkLength",
      categoryId: "3",
      value: "20",
      desc: '20"',
      hide: "n",
    },
    {
      id: 178,
      category: "SanitizeSinkLength",
      categoryId: "4",
      value: "21",
      desc: '21"',
      hide: "n",
    },
    {
      id: 179,
      category: "SanitizeSinkLength",
      categoryId: "5",
      value: "22",
      desc: '22"',
      hide: "n",
    },
    {
      id: 180,
      category: "SanitizeSinkLength",
      categoryId: "6",
      value: "24",
      desc: '24"',
      hide: "n",
    },
    {
      id: 181,
      category: "SanitizeSinkLength",
      categoryId: "7",
      value: "26",
      desc: '26"',
      hide: "n",
    },
    {
      id: 182,
      category: "SanitizeSinkLength",
      categoryId: "8",
      value: "30",
      desc: '30"',
      hide: "n",
    },
    {
      id: 183,
      category: "SanitizeSinkLength",
      categoryId: "9",
      value: "36",
      desc: '36"',
      hide: "n",
    },
  ],
  SanitizeSinkWidth: [
    {
      id: 184,
      category: "SanitizeSinkWidth",
      categoryId: "1",
      value: "28.75",
      desc: '28.75"',
      hide: "n",
    },
    {
      id: 185,
      category: "SanitizeSinkWidth",
      categoryId: "2",
      value: "31.75",
      desc: '31.75"',
      hide: "n",
    },
    {
      id: 186,
      category: "SanitizeSinkWidth",
      categoryId: "3",
      value: "34",
      desc: '34"',
      hide: "n",
    },
    {
      id: 350,
      category: "SanitizeSinkWidth",
      categoryId: "10",
      value: "24.75",
      desc: '24.75"',
      hide: "n",
    },
  ],
  SanitizeSinkDepth: [
    {
      id: 187,
      category: "SanitizeSinkDepth",
      categoryId: "1",
      value: "14",
      desc: '14"',
      hide: "n",
    },
    {
      id: 188,
      category: "SanitizeSinkDepth",
      categoryId: "2",
      value: "16",
      desc: '16"',
      hide: "n",
    },
    {
      id: 189,
      category: "SanitizeSinkDepth",
      categoryId: "3",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 190,
      category: "SanitizeSinkDepth",
      categoryId: "4",
      value: "19",
      desc: '19"',
      hide: "n",
    },
    {
      id: 191,
      category: "SanitizeSinkDepth",
      categoryId: "5",
      value: "21",
      desc: '21"',
      hide: "n",
    },
  ],
  SanitizeOverflow: [
    {
      id: 192,
      category: "SanitizeOverflow",
      categoryId: "1",
      value: "NONE",
      desc: "No",
      hide: "n",
    },
    {
      id: 193,
      category: "SanitizeOverflow",
      categoryId: "2",
      value: "Central Overflow",
      desc: "Yes",
      hide: "n",
    },
  ],
  SanitizeDrain: [
    {
      id: 196,
      category: "SanitizeDrain",
      categoryId: "1",
      value: "Standard Drain Ball Valve",
      desc: "Drain Valve Rear Exit",
      hide: "n",
    },
    {
      id: 197,
      category: "SanitizeDrain",
      categoryId: "2",
      value: "Security Drain Ball Valve",
      desc: "Security Drain Ball Valve",
      hide: "n",
    },
    {
      id: 198,
      category: "SanitizeDrain",
      categoryId: "3",
      value: "Overflow Drain Ball Valve",
      desc: "Overflow Drain Ball Valve",
      hide: "n",
    },
    // {
    //    "id":360,
    //    "category":"SanitizeDrain",
    //    "categoryId":"4",
    //    "value":"Pup-Up Drain",
    //    "desc":"Pup-Up Drain",
    //    "hide":"n"
    // }
  ],
  SanitizeDrainyes: [
    {
      id: 198,
      category: "SanitizeDrain",
      categoryId: "3",
      value: "Overflow Drain Ball Valve",
      desc: "Overflow Drain Ball Valve",
      hide: "n",
    },
  ],
  SanitizeFaucet: [
    {
      id: 199,
      category: "SanitizeFaucet",
      categoryId: "1",
      value: "FAUCET 3/4in WALL MOUNT 12 SPOUT",
      desc: "FAUCET 3/4in WALL MOUNT 12 SPOUT",
      hide: "n",
    },
    {
      id: 507,
      category: "SanitizeFaucet",
      categoryId: "2",
      value: "FAUCET 3/4in WALL MOUNT 14 SPOUT",
      desc: "FAUCET 3/4in WALL MOUNT 14 SPOUT",
      hide: "n",
    },
    {
      id: 200,
      category: "SanitizeFaucet",
      categoryId: "3",
      value: "FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT",
      desc: "FAUCET SECURITY 3/4in WALL MOUNT 12 SPOUT",
      hide: "n",
    },
    {
      id: 200,
      category: "SanitizeFaucet",
      categoryId: "4",
      value: "FAUCET SECURITY 3/4in WALL MOUNT 14 SPOUT",
      desc: "FAUCET SECURITY 3/4in WALL MOUNT 14 SPOUT",
      hide: "n",
    },
    {
      id: 201,
      category: "SanitizeFaucet",
      categoryId: "5",
      value:
        "PRE-RINSE 3/4 COMBO W/10IN SWING FAUCET,KLP34-5500-PS10(Only Encore)",
      desc: "PRE-RINSE 3/4 COMBO W/10IN SWING FAUCET,KLP34-5500-PS10(Only Encore)",
      hide: "n",
    },
    {
      id: 202,
      category: "SanitizeFaucet",
      categoryId: "6",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      hide: "n",
    },
    {
      id: 203,
      category: "SanitizeFaucet",
      categoryId: "7",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT QD ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 14 SPOUT QD ACCSY FITTING",
      hide: "n",
    },
    {
      id: 205,
      category: "SanitizeFaucet",
      categoryId: "8",
      value: "PRE-RINSE 1/2 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      desc: "PRE-RINSE 1/2 COMBO SPRAY VALVE 14 SPOUT ACCSY FITTING",
      hide: "n",
    },
    {
      id: 208,
      category: "SanitizeFaucet",
      categoryId: "10",
      value: "PRE-RINSE 3/4 COMBO SPRAY VALVE 12 SPOUT QD ACCSY FITTING",
      desc: "PRE-RINSE 3/4 COMBO SPRAY VALVE 12 SPOUT QD ACCSY FITTING",
      hide: "n",
    },
    {
      id: 209,
      category: "SanitizeFaucet",
      categoryId: "11",
      value: "PRE-RINSE 1/2 COMBO WALL MOUNT SPRAY VALVE 14 SPOUT VAC BRKR",
      desc: "PRE-RINSE 1/2 COMBO WALL MOUNT SPRAY VALVE 14 SPOUT VAC BRKR",
      hide: "n",
    },
    {
      id: 373,
      category: "PreRinseFaucet",
      categoryId: "14",
      value: "FAUCETS BY OTHERS",
      desc: "FAUCETS BY OTHERS",
      hide: "n",
    },
  ],
  SanitizeCompany: [
    {
      id: 210,
      category: "SanitizeCompany",
      categoryId: "1",
      value: "T&S",
      desc: "T&S",
      hide: "n",
    },
    {
      id: 211,
      category: "SanitizeCompany",
      categoryId: "2",
      value: "Encore",
      desc: "Encore",
      hide: "n",
    },
  ],
  PSXXX: [
    {
      id: 212,
      category: "PSXXX",
      categoryId: "1",
      value: "PS-50 CONTROL, NO HEAT",
      desc: "PS-50 CONTROL, NO HEAT",
      hide: "n",
    },
    {
      id: 213,
      category: "PSXXX",
      categoryId: "2",
      value: "PS-100 CONTROL, NO HEAT",
      desc: "PS-100 CONTROL, NO HEAT",
      hide: "n",
    },
    {
      id: 224,
      category: "PSXXX",
      categoryId: "3",
      value: "PS-100 CONTROL W/HEAT",
      desc: "PS-100 CONTROL W/HEAT",
      hide: "n",
    },
    {
      id: 214,
      category: "PSXXX",
      categoryId: "4",
      value: "PS-200 STANDARD CONTROL W/HEAT",
      desc: "PS-200 STANDARD CONTROL W/HEAT",
      hide: "n",
    },
    {
      id: 215,
      category: "PSXXX",
      categoryId: "5",
      value: "PS-200 CONTROL, NO HEAT",
      desc: "PS-200 CONTROL, NO HEAT",
      hide: "n",
    },
    {
      id: 216,
      category: "PSXXX",
      categoryId: "6",
      value: "PS-225 CONTROL, ULTRA-BRIGHT ALERT SYSTEM W/HEAT",
      desc: "PS-225 CONTROL, ULTRA-BRIGHT ALERT SYSTEM W/HEAT",
      hide: "n",
    },
    {
      id: 217,
      category: "PSXXX",
      categoryId: "7",
      value: "PS-225 CONTROL, ULTRA-BRIGHT ALERT SYSTEM NO HEAT",
      desc: "PS-225 CONTROL, ULTRA-BRIGHT ALERT SYSTEM NO HEAT",
      hide: "n",
    },
    {
      id: 218,
      category: "PSXXX",
      categoryId: "8",
      value: "PS-275 CONTROL, ULTRA-BRIGHT, DEEP CLEAN/HIGH TEMP ALERT",
      desc: "PS-275 CONTROL, ULTRA-BRIGHT, DEEP CLEAN/HIGH TEMP ALERT",
      hide: "n",
    },
  ],

  VoltagewithoutHeater: [
    {
      id: 219,
      category: "Voltage",
      categoryId: "1",
      value: "208V/1P",
      desc: "208V/1Ph/60Hz",
      hide: "n",
    },
    {
      id: 220,
      category: "Voltage",
      categoryId: "2",
      value: "208V/3P",
      desc: "208V/3Ph/60Hz",
      hide: "n",
    },
    {
      id: 221,
      category: "Voltage",
      categoryId: "3",
      value: "230V/1P",
      desc: "230V/1Ph/60Hz",
      hide: "n",
    },
    {
      id: 222,
      category: "Voltage",
      categoryId: "4",
      value: "230V/3P",
      desc: "230V/3Ph/60Hz",
      hide: "n",
    },
    {
      id: 223,
      category: "Voltage",
      categoryId: "5",
      value: "460V/3P",
      desc: "480/460V/3Ph/60Hz",
      hide: "n",
    },
  ],
  Voltage3HP: [
    {
      id: 220,
      category: "Voltage",
      categoryId: "2",
      value: "208V/3P",
      desc: "208V/3Ph/60Hz",
      hide: "n",
    },
    {
      id: 222,
      category: "Voltage",
      categoryId: "4",
      value: "230V/3P",
      desc: "230V/3Ph/60Hz",
      hide: "n",
    },
    {
      id: 223,
      category: "Voltage",
      categoryId: "5",
      value: "460V/3P",
      desc: "480/460V/3Ph/60Hz",
      hide: "n",
    },
  ],
  Generation: [
    {
      id: 226,
      category: "Generation",
      categoryId: "1",
      value: "PS6",
      desc: "PS6-(Washjets every 6 inches)",
      hide: "n",
    },
    {
      id: 227,
      category: "Generation",
      categoryId: "2",
      value: "PS3",
      desc: "PS3-(Washjets every 3 inches)",
      hide: "n",
    },
  ],
  Heater: [
    {
      id: 228,
      category: "Heater",
      categoryId: "1",
      value: "7 KW",
      desc: "7 KW heater",
      hide: "n",
    },
    {
      id: 229,
      category: "Heater",
      categoryId: "2",
      value: "2.5 KW",
      desc: "2.5 KW heater",
      hide: "n",
    },
    // {
    //    "id":457,
    //    "category":"Heater",
    //    "categoryId":"3",
    //    "value":"No",
    //    "desc":"No",
    //    "hide":"n"
    // }
  ],
  CrossRails: [
    {
      id: 231,
      category: "CrossRails",
      categoryId: "2",
      value: "Brace Mount",
      desc: "Brace Mount",
      hide: "n",
    },
    {
      id: 230,
      category: "CrossRails",
      categoryId: "1",
      value: "Welded",
      desc: "Welded",
      hide: "n",
    },
  ],
  FootType: [
    {
      id: 233,
      category: "FootType",
      categoryId: "2",
      value: "Bullet Foot",
      desc: "Bullet Foot",
      hide: "n",
    },
    {
      id: 232,
      category: "FootType",
      categoryId: "1",
      value: "Flange Foot",
      desc: "Flange Foot",
      hide: "n",
    },
  ],

  DryingRack14: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
  ],
  DryingRack17: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
  ],
  DryingRack20: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
  ],
  DryingRack21: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
  ],

  DryingRack23: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
    {
      id: 238,
      category: "DryingRack",
      categoryId: "5",
      value: "12 Pans",
      desc: "12 Pans",
      hide: "n",
    },
  ],

  DryingRack25: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
    {
      id: 238,
      category: "DryingRack",
      categoryId: "5",
      value: "12 Pans",
      desc: "12 Pans",
      hide: "n",
    },
    {
      id: 239,
      category: "DryingRack",
      categoryId: "6",
      value: "14 Pans",
      desc: "14 Pans",
      hide: "n",
    },
  ],
  DryingRack27: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
    {
      id: 238,
      category: "DryingRack",
      categoryId: "5",
      value: "12 Pans",
      desc: "12 Pans",
      hide: "n",
    },
    {
      id: 239,
      category: "DryingRack",
      categoryId: "6",
      value: "14 Pans",
      desc: "14 Pans",
      hide: "n",
    },
    {
      id: 240,
      category: "DryingRack",
      categoryId: "7",
      value: "15 Pans",
      desc: "15 Pans",
      hide: "n",
    },
  ],
  DryingRack31: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
    {
      id: 238,
      category: "DryingRack",
      categoryId: "5",
      value: "12 Pans",
      desc: "12 Pans",
      hide: "n",
    },
    {
      id: 239,
      category: "DryingRack",
      categoryId: "6",
      value: "14 Pans",
      desc: "14 Pans",
      hide: "n",
    },
    {
      id: 240,
      category: "DryingRack",
      categoryId: "7",
      value: "15 Pans",
      desc: "15 Pans",
      hide: "n",
    },
    {
      id: 241,
      category: "DryingRack",
      categoryId: "8",
      value: "16 Pans",
      desc: "16 Pans",
      hide: "n",
    },
  ],
  DryingRack: [
    {
      id: 234,
      category: "DryingRack",
      categoryId: "1",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 235,
      category: "DryingRack",
      categoryId: "2",
      value: "8 Pans",
      desc: "8 Pans",
      hide: "n",
    },
    {
      id: 236,
      category: "DryingRack",
      categoryId: "3",
      value: "9 Pans",
      desc: "9 Pans",
      hide: "n",
    },
    {
      id: 237,
      category: "DryingRack",
      categoryId: "4",
      value: "11 Pans",
      desc: "11 Pans",
      hide: "n",
    },
    {
      id: 238,
      category: "DryingRack",
      categoryId: "5",
      value: "12 Pans",
      desc: "12 Pans",
      hide: "n",
    },
    {
      id: 239,
      category: "DryingRack",
      categoryId: "6",
      value: "14 Pans",
      desc: "14 Pans",
      hide: "n",
    },
    {
      id: 240,
      category: "DryingRack",
      categoryId: "7",
      value: "15 Pans",
      desc: "15 Pans",
      hide: "n",
    },
    {
      id: 241,
      category: "DryingRack",
      categoryId: "8",
      value: "16 Pans",
      desc: "16 Pans",
      hide: "n",
    },
    {
      id: 242,
      category: "DryingRack",
      categoryId: "9",
      value: "19 Pans",
      desc: "19 Pans",
      hide: "n",
    },
  ],

  NoUndershelf: [
    {
      id: 243,
      category: "Undershelf",
      categoryId: "1",
      value: "NONE",
      desc: "No Undershelf",
      hide: "n",
    },
  ],
  UndershelfLeftSide: [
    {
      id: 243,
      category: "Undershelf",
      categoryId: "1",
      value: "NONE",
      desc: "No Undershelf",
      hide: "n",
    },
    {
      id: 452,
      category: "UndershelfLeftSide",
      categoryId: "1",
      value: "Left Undershelf Removable Upward",
      desc: "Removable Undershelf(Upturned) - left Side",
      hide: "n",
    },
    {
      id: 452,
      category: "UndershelfLeftSide",
      categoryId: "2",
      value: "Left Undershelf Removable Downward",
      desc: "Removable Undershelf(Downturned) - left Side",
      hide: "n",
    },
    {
      id: 453,
      category: "UndershelfLeftSide",
      categoryId: "3",
      value: "Left Undershelf Welded Downward",
      desc: "Welded Undershelf(Downturned) - Left Side",
      hide: "n",
    },
    {
      id: 453,
      category: "UndershelfLeftSide",
      categoryId: "4",
      value: "Left Undershelf Welded Upward",
      desc: "Welded Undershelf(Upturned) - Left Side",
      hide: "n",
    },
  ],

  UndershelfRightSide: [
    {
      id: 243,
      category: "Undershelf",
      categoryId: "1",
      value: "NONE",
      desc: "No Undershelf",
      hide: "n",
    },
    {
      id: 244,
      category: "UndershelfRightSide",
      categoryId: "1",
      value: "Right Undershelf Removable Upward",
      desc: "Removable Undershelf(Upturned) - Right Side",
      hide: "n",
    },
    {
      id: 244,
      category: "UndershelfRightSide",
      categoryId: "2",
      value: "Right Undershelf Removable Downward",
      desc: "Removable Undershelf(Downturned) - Right Side",
      hide: "n",
    },
    {
      id: 245,
      category: "UndershelfRightSide",
      categoryId: "3",
      value: "Right Undershelf Welded Upward",
      desc: "Welded Undershelf(Upturned) - Right Side",
      hide: "n",
    },
    {
      id: 245,
      category: "UndershelfRightSide",
      categoryId: "4",
      value: "Right Undershelf Welded Downward",
      desc: "Welded Undershelf(Downturned) - Right Side",
      hide: "n",
    },
  ],

  Undershelf: [
    {
      id: 243,
      category: "Undershelf",
      categoryId: "1",
      value: "NONE",
      desc: "No Undershelf",
      hide: "n",
    },
    {
      id: 244,
      category: "Undershelf",
      categoryId: "2",
      value: "Right Undershelf Removable Upward",
      desc: "Removable Undershelf(Upturned) - Right Side",
      hide: "n",
    },
    {
      id: 244,
      category: "Undershelf",
      categoryId: "2",
      value: "Right Undershelf Removable Downward",
      desc: "Removable Undershelf(Downturned) - Right Side",
      hide: "n",
    },
    {
      id: 245,
      category: "Undershelf",
      categoryId: "3",
      value: "Right Undershelf Welded Upward",
      desc: "Welded Undershelf(Upturned) - Right Side",
      hide: "n",
    },
    {
      id: 245,
      category: "Undershelf",
      categoryId: "3",
      value: "Right Undershelf Welded Downward",
      desc: "Welded Undershelf(Downturned) - Right Side",
      hide: "n",
    },
    {
      id: 246,
      category: "Undershelf",
      categoryId: "7",
      value: "Both Undershelf Welded Upward",
      desc: "Welded undershelf (Upturned) - Both Sides ",
      hide: "n",
    },
    {
      id: 246,
      category: "Undershelf",
      categoryId: "7",
      value: "Both Undershelf Welded Downward",
      desc: "Welded undershelf (Downturned) - Both Sides ",
      hide: "n",
    },
    {
      id: 452,
      category: "Undershelf",
      categoryId: "4",
      value: "Left Undershelf Removable Upward",
      desc: "Removable Undershelf(Upturned) - left Side",
      hide: "n",
    },
    {
      id: 452,
      category: "Undershelf",
      categoryId: "4",
      value: "Left Undershelf Removable Downward",
      desc: "Removable Undershelf(Downturned) - left Side",
      hide: "n",
    },
    {
      id: 453,
      category: "Undershelf",
      categoryId: "5",
      value: "Left Undershelf Welded Downward",
      desc: "Welded Undershelf(Downturned) - Left Side",
      hide: "n",
    },
    {
      id: 453,
      category: "Undershelf",
      categoryId: "5",
      value: "Left Undershelf Welded Upward",
      desc: "Welded Undershelf(Upturned) - Left Side",
      hide: "n",
    },
    {
      id: 454,
      category: "Undershelf",
      categoryId: "6",
      value: "Both Undershelf Removable Upward",
      desc: "Removable undershelf (Upturned) - Both Sides ",
      hide: "n",
    },
    {
      id: 454,
      category: "Undershelf",
      categoryId: "6",
      value: "Both Undershelf Removable Downward",
      desc: "Removable undershelf (Downturned) - Both Sides ",
      hide: "n",
    },
  ],
  Overshelf: [
    {
      id: 247,
      category: "Overshelf",
      categoryId: "1",
      value: "NONE",
      desc: "No Overshelf",
      hide: "n",
    },
    {
      id: 248,
      category: "Overshelf",
      categoryId: "2",
      value: "45 Degree Overshelf",
      desc: "Texas-Slotted Over Shelf with Double Pot Rack",
      hide: "n",
    },
    {
      id: 450,
      category: "Overshelf",
      categoryId: "3",
      value: "45 Degree Overshelf",
      desc: "Non Texas-Slotted Over Shelf with Double Pot Rack",
      hide: "n",
    },
    // {
    //   id: 443,
    //   category: "Overshelf",
    //   categoryId: "4",
    //   value: "45 Degree Overshelf",
    //   desc: "Drying shelf with Double pot rack",
    //   hide: "n",
    // },
    {
      id: 444,
      category: "Overshelf",
      categoryId: "5",
      value: "90 Degree Overshelf",
      desc: "Texas-Slotted Over Shelf with Single Pot Rack",
      hide: "n",
    },
    {
      id: 451,
      category: "Overshelf",
      categoryId: "9",
      value: "90 Degree Overshelf",
      desc: "Drying Shelf with Pot Rack",
      hide: "n",
    },
    {
      id: 446,
      category: "Overshelf",
      categoryId: "7",
      value: "90 Degree Overshelf",
      desc: "Non Texas-Slotted Over Shelf with Single Pot Rack",
      hide: "n",
    },
    {
      id: 447,
      category: "Overshelf",
      categoryId: "8",
      value: "WithoutPot",
      desc: "Non Texas-Slotted Over Shelf without Pot Rack",
      hide: "n",
    },
    {
      id: 448,
      category: "Overshelf",
      categoryId: "9",
      value: "WithoutPot",
      desc: "Texas-Slotted Over Shelf without Pot Rack",
      hide: "n",
    },
    {
      id: 449,
      category: "Overshelf",
      categoryId: "10",
      value: "WithoutPot",
      desc: "Drying Shelf without Pot Rack",
      hide: "n",
    },
  ],

  DisposerMake: [
    {
      id: 374,
      category: "DisposerMake",
      categoryId: "1",
      value: "SALVAJOR",
      desc: "SALVAJOR",
      hide: "n",
    },
    {
      id: 375,
      category: "DisposerMake",
      categoryId: "2",
      value: "INSINKERATOR(ISE)",
      desc: "INSINKERATOR(ISE)",
      hide: "n",
    },
    {
      id: 376,
      category: "DisposerMake",
      categoryId: "3",
      value: "HOBART",
      desc: "HOBART",
      hide: "n",
    },
    { id: 505, 
      category: "DisposerMake",
     categoryId: "4", 
      value: "Salvajor",
      desc: "TBD/info not available", 
      hide: "n", 
    },
    
  ],
  DisposerConeMake: [
    {
      id: 377,
      category: "DisposerConeMake",
      categoryId: "1",
      value: "SALVAJOR",
      desc: "SALVAJOR",
      hide: "n",
    },
    {
      id: 378,
      category: "DisposerConeMake",
      categoryId: "2",
      value: "HOBART",
      desc: "HOBART",
      hide: "n",
    },
    {
      id: 379,
      category: "DisposerConeMake",
      categoryId: "3",
      value: "INSINKERATOR(ISE)",
      desc: "INSINKERATOR(ISE)",
      hide: "n",
    },
    {
      id: 380,
      category: "DisposerConeMake",
      categoryId: "4",
      value: " REDGOAT",
      desc: " REDGOAT",
      hide: "n",
    },
    {
      id: 381,
      category: "DisposerConeMake",
      categoryId: "5",
      value: "SOMAT",
      desc: "SOMAT",
      hide: "n",
    },
    {
      id: 382,
      category: "DisposerConeMake",
      categoryId: "6",
      value: " WASTEKING",
      desc: " WASTEKING",
      hide: "n",
    },
    {
      id: 383,
      category: "DisposerConeMake",
      categoryId: "7",
      value: "MASTER",
      desc: "MASTER",
      hide: "n",
    },
    { id: 506, 
      category: "DisposerConeMake",
     categoryId: "8", 
      value: "TBD",
      desc: "TBD/info not available", 
      hide: "n", 
    },
    // {
    //   id: 505,
    //   category: "DisposerConeMake",
    //   categoryId: "8",
    //   value: "others",
    //   desc: "TBD",
    //   hide: "n",
    // },
  ],
  DisposerConeSize: [
    {
      id: 384,
      category: "DisposerConeSize",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },
    {
      id: 385,
      category: "DisposerConeSize",
      categoryId: "2",
      value: "15",
      desc: '15"',
      hide: "n",
    },
    {
      id: 386,
      category: "DisposerConeSize",
      categoryId: "3",
      value: "18",
      desc: '18"',
      hide: "n",
    },
  ],
  CollectorMake: [
    {
      id: 387,
      category: "CollectorMake",
      categoryId: "1",
      value: "SALVAJOR",
      desc: "SALVAJOR",
      hide: "n",
    },
    { id: 388, 
      category: "DisposerConeMake",
     categoryId: "8", 
      value: "Salvajor",
      desc: "TBD/info not available", 
      hide: "n", 
    },
    // {
    //   id: 388,
    //   category: "CollectorMake",
    //   categoryId: "2",
    //   value: "INSINKERATOR(ISE)",
    //   desc: "INSINKERATOR(ISE)",
    //   hide: "n",
    // },
    // {
    //   id: 506,
    //   category: "CollectorMake",
    //   categoryId: "3",
    //   value: "others",
    //   desc: "TBD",
    //   hide: "n",
    // },
  ],
  CollectorModel: [
    {
      id: 389,
      category: "CollectorModel",
      categoryId: "1",
      value: "S914",
      desc: "S914",
      hide: "n",
    },
    {
      id: 390,
      category: "CollectorModel",
      categoryId: "2",
      value: "P914",
      desc: "P914",
      hide: "n",
    },
    {
      id: 391,
      category: "CollectorModel",
      categoryId: "3",
      value: "SM",
      desc: "SM",
      hide: "n",
    },
    {
      id: 392,
      category: "CollectorModel",
      categoryId: "4",
      value: "PSM",
      desc: "PSM",
      hide: "n",
    },
    {
      id: 504,
      category: "CollectorModel",
      categoryId: "5",
      value: "300-PSM",
      desc: "300-PSM",
      hide: "n",
    },
  ],
  DisposerSinkLength: [
    {
      id: 393,
      category: "DisposerSinkLength",
      categoryId: "1",
      value: "12",
      desc: '12"',
      hide: "n",
    },
    {
      id: 394,
      category: "DisposerSinkLength",
      categoryId: "2",
      value: "14",
      desc: '14"',
      hide: "n",
    },
    {
      id: 395,
      category: "DisposerSinkLength",
      categoryId: "3",
      value: "16",
      desc: '16"',
      hide: "n",
    },
    {
      id: 396,
      category: "DisposerSinkLength",
      categoryId: "4",
      value: "18",
      desc: '18"',
      hide: "n",
    },
    {
      id: 397,
      category: "DisposerSinkLength",
      categoryId: "5",
      value: "20",
      desc: '20"',
      hide: "n",
    },
    {
      id: 398,
      category: "DisposerSinkLength",
      categoryId: "6",
      value: "24",
      desc: '24"',
      hide: "n",
    },
  ],
  DisposerSinkWidth: [
    {
      id: 399,
      category: "DisposerSinkWidth",
      categoryId: "1",
      value: "24.75",
      desc: '24.75"',
      hide: "n",
    },
    {
      id: 400,
      category: "DisposerSinkWidth",
      categoryId: "2",
      value: "28.75",
      desc: '28.75"',
      hide: "n",
    },
  ],
  DisposerDepth: [
    {
      id: 401,
      category: "DisposerDepth",
      categoryId: "1",
      value: "5.375",
      desc: '5.375"',
      hide: "n",
    },
    {
      id: 401,
      category: "DisposerDepth",
      categoryId: "1",
      value: "4",
      desc: '4"',
      hide: "n",
    },
    {
      id: 401,
      category: "DisposerDepth",
      categoryId: "1",
      value: "5",
      desc: '5"',
      hide: "n",
    },
  ],
  MotorHPwithoutHeater: [
    {
      id: 456,
      category: "MotorHP",
      categoryId: "2",
      value: "2HP",
      desc: "2HP",
      hide: "n",
    },
  ],
  MotorHPwithHeater: [
    {
      id: 456,
      category: "MotorHP",
      categoryId: "2",
      value: "2HP",
      desc: "2HP",
      hide: "n",
    },
    {
      id: 458,
      category: "MotorHP",
      categoryId: "3",
      value: "3HP",
      desc: "3HP",
      hide: "n",
    },
  ],
  AWISheetPanRack: [
    {
      id: 504,
      category: "AWISheetPanRack",
      categoryId: "5",
      value: "NONE",
      desc: "None",
      hide: "n",
    },
    {
      id: 459,
      category: "AWISheetPanRack",
      categoryId: "1",
      value: "2 sheet pan rack set",
      desc: "2 sheet pan rack set",
      hide: "n",
    },
    {
      id: 500,
      category: "AWISheetPanRack",
      categoryId: "2",
      value: "6 sheet pan rack set",
      desc: "6 sheet pan rack set",
      hide: "n",
    },
    {
      id: 501,
      category: "AWISheetPanRack",
      categoryId: "3",
      value: "10 sheet pan rack set",
      desc: "10 sheet pan rack set",
      hide: "n",
    },
    {
      id: 502,
      category: "AWISheetPanRack",
      categoryId: "4",
      value: "12 sheet pan rack set",
      desc: "12 sheet pan rack set",
      hide: "n",
    },
    {
      id: 503,
      category: "AWISheetPanRack",
      categoryId: "5",
      value: "18 sheet pan rack set",
      desc: "18 sheet pan rack set",
      hide: "n",
    },
  ],
};

export { referencedata };
